### ISSUE TITLE
Slides Jump back (from 112 to 27)

### ISSUE THREAD

**Issue by threecourse** [cvpaperchallenge/CVPR2018_Survey#286]
slides/index.pugに重複があり(Smart_Sparse_Contours_to_Represent_and_Edit_Images.pug)、
#112のあとに#27に飛ばされてしまいます。

**Comment by naklabkota** [comment]
重複部分を削除いたしました．
ご迷惑をおかけして申し訳ございません．

**Comment by threecourse** [comment]
いえいえ、とても勉強になるプロジェクトをありがとうございます！


2018年6月15日(金) 1:01 naklabkota <notifications@github.com>:
