### ISSUE TITLE
特定のページに直接アクセスできません

### ISSUE THREAD

**Issue by errno-mmd** [cvpaperchallenge/CVPR2018_Survey#289]
@CVpaperChalleng のツイートのリンクを辿って
https://cvpaperchallenge.github.io/CVPR2018_Survey/#/_2D3D_Pose_Estimation_and_Action_Recognition_using_Multitask_Deep_Learning
にアクセスしたところ、このページは表示されず、先頭のページ
https://cvpaperchallenge.github.io/CVPR2018_Survey/#/Multi-Level_Fusion_Based_3D_Object_Detection_From_Monocular_Images
に飛ばされます。
ブラウザ: Firefox 60.0.2 (64ビット) および Chrome 66.0.3359.181 (64ビット)、OS: Windows10

**Comment by suzuryo3893** [comment]
ご報告ありがとうございます．現象確認しました．
対応を検討していますが，HTML由来の想定外動作のように思われ，解決のめどは立っておりません．

**Comment by suzuryo3893** [comment]
暫定的に，以下のアドレスでアクセスできるようにしました．
https://cvpaperchallenge.github.io/CVPR2018_Survey/#/TAG_2D3D_Pose_Estimation_and_Action_Recognition_using_Multitask_Deep_Learning

**Comment by errno-mmd** [comment]
ありがとうございます。アクセスできました。当面はそのURLで利用させていただきたいと思います。

**Comment by suzuryo3893** [comment]
パーマネントリンクの命名規則を変更いたしました．
以降，該当スライドはこちらのURLでアクセス可能です．
https://cvpaperchallenge.github.io/CVPR2018_Survey/#/ID_2D3D_Pose_Estimation_and_Action_Recognition_using_Multitask_Deep_Learning

**Comment by errno-mmd** [comment]
無事アクセスできることを確認しました。ありがとうございます。
